apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-source-0
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <source-storage-class>
  resources:
    requests:
      storage: 5Gi