apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsync-helper-log-0
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <dest-storage-class>
  resources:
    requests:
      storage: 1Gi